### ISSUE TITLE
Removing Collection Folder Causes Type Error

### ISSUE THREAD

**Issue by JacobRichardson** [wankdanker/symdb#1]
Removing a collection causes a type error. The collection was removed from /opt/database/collection_name.
```
node_modules/symdb/lib/index-search.js:58
                dirs = dirs.filter(function (a) {
TypeError: Cannot read property 'filter' of undefined
    at node_modules/symdb/lib/index-search.js:58:29
    at node_modules/symdb/index.js:105:20
    at FSReqWrap.oncomplete (fs.js:141:20)
```
Inserting the following line on line 55 appears to fix the issue.
```js
dirs = dirs || [];
```

**Comment by wankdanker** [comment]
@JacobRichardson What method were you calling? And was the `/opt/database/collection_name` directory removed manually?
